version: '3.3'

name: remindr-database-dev

services:
  postgres:
    container_name: remindr-database-dev
    image: postgres
    environment:
      - POSTGRES_DB=remindr_db
      - POSTGRES_USER=remindr_dev
      - POSTGRES_PASSWORD=r3m1nd3rd3v
    ports:
      - '5433:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
