import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import NavBar from '~/components/NavBar';
import {Separator} from '~/components/ui/separator';
import Providers from '~/providers/Providers';
import {cn} from '~/libs/utils';
import {Toaster} from '~/components/ui/toaster';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
                                     children
                                   }: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={cn(inter.className, 'dark')}>
    <body
      className={`flex flex-col items-center min-h-screen w-full`}>
    <Providers>
      <NavBar/>
      <Separator/>
      <main className='flex flex-grow justify-center items-center p-4 w-full'>
        {children}
        <Toaster/>
      </main>
    </Providers>
    </body>
    </html>
  );
}
